[tool.poetry]
name = "bot"
version = "1"
description = "py bot"
authors = ["Vladimir  <vladimir.zaitsev@jointoit.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
